name: redux_dev_tools
description: Time Travel Dev Tools for Dart Redux
version: 0.1.1
homepage: https://gitlab.com/brianegan/redux_dev_tools
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  redux: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^0.12.0
