name: redux_dev_tools
description: Time Travel Dev Tools for Dart Redux
version: 0.5.1
homepage: https://github.com/brianegan/redux_dev_tools
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  redux: ">=4.0.0 <5.0.0"

dev_dependencies:
  coverage: ">=0.13.0 <0.14.0"
  test: ">=1.0.0 <2.0.0"
